#!/bin/sh
uci -q batch <<-EOF
	set system.@system[0].hostname='MainRouter'
	set system.@system[0].zonename='Asia/Shanghai'
	set system.@system[0].timezone='CST-8'
	delete system.ntp.server
	# add_list system.ntp.server='ntp.tencent.com'
	add_list system.ntp.server='ntp1.aliyun.com'
	# add_list system.ntp.server='ntp.ntsc.ac.cn'
	add_list system.ntp.server='cn.ntp.org.cn'
EOF
uci commit system

# set network lan...
uci -q batch <<-EOF
	set network.lan.proto='static'
	set network.lan.device='br-lan'
	set network.lan.ipaddr='192.168.100.1'
        set network.lan.gateway='192.168.100.1'
	set network.lan.netmask='255.255.255.0'
	# set network.lan.broadcast='192.168.100.255'
	# set network.lan.dns='114.114.114.114 223.5.5.5'
EOF
uci commit network

# set network lan dhcp server on
uci -q batch <<-EOF
       set dhcp.lan.start='50'
       set dhcp.lan.limit='150'     
       set dhcp.lan.ignore='0'
       set dhcp.lan.force='1'
EOF
uci commit dhcp


 sed -i '/REDIRECT --to-ports 53/d' /etc/firewall.user
 echo 'iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53' >> /etc/firewall.user
 echo 'iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53' >> /etc/firewall.user

 echo '[ -n "$(command -v ip6tables)" ] && ip6tables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53' >> /etc/firewall.user
 echo '[ -n "$(command -v ip6tables)" ] && ip6tables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53' >> /etc/firewall.user

# Set file /etc/openwrt_release
sed -i '/DISTRIB_ID/d' /etc/openwrt_release
echo "DISTRIB_ID='MainRouter '" >> /etc/openwrt_release
sed -i '/DISTRIB_REVISION/d' /etc/openwrt_release
echo "DISTRIB_REVISION='$(date "+%Y-%m-%d")'" >> /etc/openwrt_release
sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
echo "DISTRIB_DESCRIPTION='MainRouter '" >> /etc/openwrt_release
sed -i '/DISTRIB_LASTMODIFIELD/d' /etc/openwrt_release
echo "DISTRIB_LASTMODIFIELD='Compiled by Wangmingde $(date "+%Y-%m-%d %H:%M:%S")'" >> /etc/openwrt_release

# Set Default password of root
sed -i 's/root:.*/root:$1$O7GrRZCz$k1qdGMkJy29pEppAUhvZT0:19547:0:99999:7:::/' /etc/shadow

# Set banner
mv -f /etc/gssiwmd_banner /etc/banner

exit 0
